"""empty message

Revision ID: 542c0e469b4e
Revises: d0307a2350b1
Create Date: 2021-07-15 19:39:37.502487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542c0e469b4e'
down_revision = 'd0307a2350b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
