"""empty message

Revision ID: d3f8dbdc90fc
Revises: 542c0e469b4e
Create Date: 2021-07-15 19:47:12.400155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f8dbdc90fc'
down_revision = '542c0e469b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.drop_column('products', 'active')
    op.drop_column('categories', 'active')
    # ### end Alembic commands ###
